### ISSUE TITLE
add Stderr column to the phenotype table

### ISSUE THREAD

**Issue by nmenda** [GMOD/Chado#135]
much needed for phenotype analysis
We use this a lot in BreedBase

**Comment by scottcain** [comment]
The idea being a field to just capture the contents of stderr from an analysis? Seems reasonable.

**Comment by spficklin** [comment]
Could you store that as a recrod in the analysisprop table?

**Comment by nmenda** [comment]
@scottcain yes, this is for the stderr value. 

@spficklin we were thinking of phenotypeprop, but being able to store standard error in the phenotype table would be preferable since a lot of random metadata is dumped into phenotypeprop. 
BreedBase does not use the analysis module (we use nd_experiment to link a group of phenotypes to a project/trial) and already has too many joins. 
With millions of data points for phenotyping experiments adding more joins will make querying too slow.

**Comment by laceysanderson** [comment]
Hi @nmenda, so just to confirm you want to add a column for the statistical standard error for the phenotypic value? 

Normally this data would be stored in the phenotypeprop table for sure but I hear you on the data volume with the number of joins being problematic. My general rule of thumb is that it should be added to the base table if (a) it applies to most of the records in that table and if (b) it can be fully described as a single value. 

I think (a) is true for stderr of phenotypic data points but I worry about (b) because standard error is often estimated. If you use the phenotypeprop table you can indicate whether the value is an estimate and how it is estimated using the property type term. Personally I also always want to know the sample size whenever standard error is estimated as that is critical to deciding how much I trust the estimate. How are you storing this?

**Comment by nmenda** [comment]
those are good points @laceysanderson. We will try to implement Stderr  in phenoytpeprop and see how it goes.
