### ISSUE TITLE
1.4 schema documentation

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#36]
The old wiki documentation was generated via a python script.    It is now out of date and we dont have an easy way to update it.  we also don't want to lose the comments and changes in the existing wiki.

* Change the python script to somehow update?
* Use a more brand name documentation generator?  That can somehow deal with this?
* Deprecate the old documentation and point people to a new docs that is generated via a brand name documentation generator?

**Comment by bradfordcondon** [comment]
I believe the consensus is to deprecate the old documentation and host the  > 1.4 documentation on github (hopefully still generated automatically from the code)

**Comment by laceysanderson** [comment]
I'm excited about this one!!! I've been bringing up updated documentation for awhile now ;-) Does anyone have suggestions for a "brand name" documentation generator?

**Comment by bradfordcondon** [comment]
i love the markdown support

but i think scalability is a consideration (unless it gets sorted by module automatically?  Then it migth be manageable?)  The diagrams look cool but those also might get very messy fast

**Comment by laceysanderson** [comment]
You can see a SchemaSpy version of Chado v1.3 documentation here: https://preview.c9users.io/laceysanderson/schemaspy/docs/index.html 
This is just my first run at it with all the defaults.

Some things to note:
- Because there are so many tables, the table listing is paged. This is mitigated by a really quick table search (top right corner of table fieldset).
- As expected the full ER diagram is useless (**laughs**) I suspect this will be the case with any tool thanks to the complexity that is chado.
- There are ER diagrams for each table that show related tables (huge plus) but the defaults don't show all columns (I'm going to see if I can change this but a cursory look doesn't seem promising).
- "Orphan" tables seem to be simply ones without foreign keys. I would simply remove this tab in the finished documentation. (I would also remove relationships and anomalies since I feel they are useless as is).

NOTE: This is done as a Cloud9 "workspace" which can easily be cloned, saved, shared but it was basically a matter of setting up Java8, graphviz, downloading pgsql driver and schemaspy and running a single command 👍  (Overkill [README](https://static.c9.io/nc-3.1.4094-ea37d9f2/static/plugins/c9.ide.preview.markdown/markdown.html?host=https://ide.c9.io&id=markdown1) )

**Comment by bradfordcondon** [comment]
Looks pretty nice.  I'm surprised there are so few free alternatives.  One i found was [pg-table-markdown](https://github.com/vokal/pg-table-markdown) which would create markdown files which we could then host on this repo's [wiki page](https://github.com/GMOD/Chado/wiki). 
I might try it out but am missing the python dev modules

**Comment by laceysanderson** [comment]
I was also surprised at the lack of robust free alternatives. I worry that pg-table-markdown may no longer be maintained... I think I can customize the page templates for SchemaSpy so that each time we generate the docs our templates are used instead of the default ones. This would allow me to make the pages simpler and more tailored to a schema (rather then a database) doc. 

We can use GitHub pages to host the output and it might be good that people are not tempted to edit it directly like they would be in a wiki (manual edits would be lost between versions).

**Comment by bradfordcondon** [comment]
I'm not happy with pg-table-markdown.  It makes nice table summaries but doesnt get the comments so its worthless unless im missing something (see below for analysis).

Sounds like SchemaSpy is the way to go.

### analysis 

Column | Type | Default | Nullable 
--- | --- | --- | --- 
analysis_id | bigint | nextval('chado.analysis_analysis_id_seq'::regclass) | NO 
name | character varying | None | YES 
description | text | None | YES 
program | character varying | None | NO 
programversion | character varying | None | NO 
algorithm | character varying | None | YES 
sourcename | character varying | None | YES 
sourceversion | character varying | None | YES 
sourceuri | text | None | YES 
timeexecuted | timestamp without time zone | now() | NO

**Comment by laceysanderson** [comment]
Customizing of SchemaSpy is really easy (once you find the undocumented method for doing so)! I'm going to go through and make the changes I would like to see. My intent is to make the style simpler and remove the unnecessary/n.a. bits, as well as, to brand it with GMOD :-)

@bradfordcondon you commented that it's maybe "less useful for newer users". What are some of the features you think would make it more useful for new users? :-)

**Comment by bradfordcondon** [comment]
@laceysanderson there are 209 tables listed, which is pretty overwhelming.  It's nice to have a place to start.

The current documentation is broken up into modules and each module has an introduction/overview.  If we could organize the schemaspy output somehow, or allow overviews by module, that would help. 

* Organize and summarize modules/sets of tables somehow
* Include introductory text from the wiki thats not in the sql table comments

**Comment by laceysanderson** [comment]
You can see a **simplified & branded** SchemaSpy version of Chado v1.3 documentation here: https://preview.c9users.io/laceysanderson/schemaspy/chado-docs/v1.3/index.html

In reference to breaking tables out by module and including the module-specific documentation: Modules are only denoted by SQL comments which are not even loaded into the resulting database. This means we **cannot break the SchemaSpy documentation down by module** :-(. Furthermore, the additional documentation is no where in the SQL and thus cannot end up in the SchemaSpy generated documentation.

## Possible Solutions:
1. Modify the Module-specific documentation on the GMOD wiki so that the tables section for each module is simply a list of table names linked to the specific pages in the SchemaSpy documentation. This would cause jumping back and forth between websites :-(
2. Move all the documentation from the GMOD wiki to GitHub pages. Module-specific documentation would still be separate from the SchemaSpy table docs but they would have a consistent style and location.

### NOTES:
- Both solutions would cause lots of jumping back between module and table-specific pages.
- Solution 2 could be done using a page generator like Jenkins to make modifying the documentation easier then straight HTML but regardless it would require pull requests rather then directly editing a wiki page.
- You can see in [this demo](https://preview.c9users.io/laceysanderson/schemaspy/chado-docs/index.html)  that I would make multiple versions of chado documentation available with `[github pages]/current` always pointing to the current version. This allows users to bookmark pages knowing they will always see the current definitions AND it allows the linking in module-specific documentation to always be current.
- Notice that the schema version is indicated at the top of every page in the SchemaSpy documentation and the current version is highlighted on the demo page. 
- Regardless of the choice chosen I'm volunteering to implement it so don't let amount of work sway your decision ;-p

**My Choice:** I prefer solution 2 because I'm a bit obsessed with consistent pages and not hoping between websites. Furthermore, as most people know, I hate Wiki Markup ;-P

@bradfordcondon, @scottcain and @spficklin **could you weigh in on which solution you prefer? Also feel free to provide feedback on the SchemaSpy documentation and demo page.** 👍

**Comment by spficklin** [comment]
If we wanted to be industrious I suppose we could create a separate schema for each module and load the module tables only into that schema.  That would simply the ER diagrams and bring back the modular organization of the tables.  It would be relatively easy to do as each module has a separate SQL file but I don't know how hard that would be for someone to do each module separately with SchemaSpy.  Can it be automated?   If so then a Docker image may be in order that has everything ready to go and we can just fire it up and rebuild when changes are made.

**Comment by scottcain** [comment]
Of course, right now each module has it's own SQL file.  The problem is that they have foreign key constraints that go "outside" each module, which probably would give schemaspy a hard time, though it is possible that it has some good way of representing those "unsatisfied" constraints.

For automation, Schemaspy.org seems to be built on an open source Java component that can be run on the command line, so yes, it seems like we could create a docker image that we would just fire up when we want to generate documentation.  On the other hand, the jar file for schemaspy.jar was last touched on SourceForge in 2010.  Who knows if it still works.  See http://schemaspy.sourceforge.net/

**Comment by laceysanderson** [comment]
- Good idea @spficklin! SchemaSpy supports multiple schema's so I'll see what happens when I load each module as it's own schema ***fingers crossed***
- @scottcain development of SchemaSpy has moved to GitHub: https://github.com/schemaspy/schemaspy. It's still actively developed and has a good community :-)
- Also, I have SchemaSpy working already. You can see chado documentation here: https://preview.c9users.io/laceysanderson/schemaspy/chado-docs/v1.3/index.html 
- We can definitely automate things (although me & docker still don't get along so someone else will have to take that on ;-) ). I'll write a quick script when I'm loading in the module SQL as separate schema's so that part will be done.

**Comment by scottcain** [comment]
@laceysanderson OK, good to hear about continued development.  I was a little worried that it had been taken closed source.  The other question still stands: what if I take modules/sequence/sequence.sql and try to run it?  Does it puke because the cvterm table isn't present?

**Comment by laceysanderson** [comment]
@scottcain I'll try it tonight once I get the kids to sleep (T-2hrs) and let you know 👍  I have a cloud dev set up for SchemaSpy already so it'll be quickest for me to test.

**Comment by laceysanderson** [comment]
### Screenshots
**Adding screenshots here so I can delete the previously linked to docs.**
#### "Customized & Branded" SchemaSpy output for all tables (not broken down by module)
The following screenshots are generated using custom "branded" templates for SchemaSpy which I will put in a github repo soon ;-) Everything is automatically generated making it easy to update documentation in the future.
- Main Page: A paged view of all the tables... More then a little overwhelming but functional and fast. 
[schemaspy-tablepage-alltables](https://user-images.githubusercontent.com/1566301/35024608-179c28c0-fb06-11e7-9cbc-913ee496de7e.png)
- Main Page searched for "project": the table search is ridiculously fast making the long listing much more functional. [schemaspy-tablepage-projectsearch](https://user-images.githubusercontent.com/1566301/35024610-1b2b3d96-fb06-11e7-80a8-15f1be48c081.png)
- Stock Page: Each table has it's own page with description, columns, indexes and a small ER diagram. [schemaspy-stockpage](https://user-images.githubusercontent.com/1566301/35024614-2200eaf8-fb06-11e7-9e2d-d6979798299c.png)
- Hard-coded Docs homepage which would link to all versions of schema docs as suggested above. [chado-homepage](https://user-images.githubusercontent.com/1566301/35024850-6bc5f1fa-fb07-11e7-816c-eff1f34c86d8.png)

Now to see if I can get it broken down by module as per @spficklin suggestion.

**Comment by laceysanderson** [comment]
#### Short Answer: It works beautifully!
- There is now a page with all tables for a given module.
- Table pages still show foreign keys to tables in other modules and links work!
- There is a module ER diagram: this shows all the tables in the current module, as well as, tables referred to by FK (e.g. the cv module diagram has the dbxref/db tables). This may still end up over complicated but seems better then before.

#### Process:
I created a "chado" database with a "schema" for each module. Then I used the module-specific SQL files to populate each "schema" with the tables for that module. I manipulated the search_path to ensure that FK could cross "schema's". Then I used SchemaSpy to generate documentation for each "schema" (module).

#### Need Feedback:
Of course the extra documentation on the wiki module pages is still not available since it's not in the SQL but we could fix that using comments with markdown in them. I would propose adding a markdown file to each module directory. Then we can script adding the contents of that file as a comment on the "schema". This way that documentation would end up in the SchemaSpy docs but still be easy to update and access in the chado repo. Furthermore, it will still be useful if we go with a different documentation method in the future. **Thoughts? Other ideas? Concerns?**

_**Anyway I'll play more with it tomorrow. I've only done a small test at this point (3 modules) and can see the need for some changes in my custom templates.**_

**Comment by bradfordcondon** [comment]
@laceysanderson Thank you so much, it sounds like we are getting the best of both worlds this way.

>Of course the extra documentation on the wiki module pages is still not available since it's not in the SQL but we could fix that using comments with markdown in them. I would propose adding a markdown file to each module directory. Then we can script adding the contents of that file as a comment on the "schema". This way that documentation would end up in the SchemaSpy docs but still be easy to update and access in the chado repo. Furthermore, it will still be useful if we go with a different documentation method in the future.

This is more or less what I would propose.    A `readme.md` file for each module in the directory so it's under version control and easily editable.

No further suggestions or criticisms, i think this will be a huge improvement to current documentation, look good, be easier to maintain, and be useful for new users.

**Comment by laceysanderson** [comment]
#### Quick Update
- I'm going to do this in 2 stages: 1) table docs (all + module), 2) markdown extended docs. 
- Stage 1 is almost done. You can see the scripts for generating the documentation here: https://github.com/laceysanderson/generate_chadodocs/ 
    - Need to use parameters rather then hardcoding
    - Fix weird error loading in full chado 1.31 default.sql
    - Complete Repo readme

## Screenshots
### Home page of the Chado documentation. Shows all chado tables and links to modules.
![home-all_chado_tables](https://user-images.githubusercontent.com/1566301/35080724-0a7f0886-fbd5-11e7-88f1-9682ba69894c.png)

### DB Module page which will contain module-specific documentation
![db_module-tables](https://user-images.githubusercontent.com/1566301/35080735-145ca886-fbd5-11e7-85b8-89ed0b4e2fc9.png)

### Example of a Table page accessed from the full table listing
![featureloc_table](https://user-images.githubusercontent.com/1566301/35080740-1b000d86-fbd5-11e7-8561-ec2604d58dac.png)

### Example of a table page accessed from a module listing
![db_module-db_table](https://user-images.githubusercontent.com/1566301/35080810-90b34d54-fbd5-11e7-9fec-a29e0d34c0c6.png)

**Comment by laceysanderson** [comment]
@scottcain & @scottcain: Once I get the last couple of point in stage 1 done, can I put this documentation up on GitHub pages? :-D

Any style changes or additional concerns?

**Comment by spficklin** [comment]
I like it!  I noticed though that the schema name is present in the ER diagram. For example the db table is a FK for the stock.stockcollection_db table.  But when folks install Chado they won't have a stock prefix to the table which may cause confusion.  Am I just being pedantic or would that really be a problem?

**Comment by bradfordcondon** [comment]
I don't think you're being pedantic: it could be confusing for users new to databases.
That said if it isn't fixable without combining all the modules together, it could be addressed with a note in the documentation instead.  I like the current layout more than i'm bothered by this :)

**Comment by bradfordcondon** [comment]
I found out that SchemaSpy uses the [AdminLTE style template](https://adminlte.io/) which @almasaeed2010 created.  

He could probably help with prettifying the docs, a lot.

**Comment by laceysanderson** [comment]
Good catch @spficklin, I didn't notice that! We can definitely put in a note so users know thats the "module" and not to include it in queries. Furthermore, I'll see how easy it is to customize the diagrams -those templates might be packaged within the jar **hopefully not!**

Thats cool that @almasaeed2010 made the templates -small world! I'm having a really easy time customizing the docs so far :-) I'm just trying not to go all out, since I have limited time ;-)

**Comment by laceysanderson** [comment]
Ok, I've done some digging and it looks like everything related to how graphviz draws the ER diagrams is buried within the JAR :-( This means I can't remove the prefix from tables in a separate module.

Instead I've tried @bradfordcondon's suggestion and added a note above the ER diagram. Thoughts? Suggestions? Is that obvious enough do you think (I don't like yelling at people ;-) )?
![db_module-db_table_with_note](https://user-images.githubusercontent.com/1566301/35114420-4b2fe2fe-fc4a-11e7-8c7d-df3170e3b44e.png)

**Comment by bradfordcondon** [comment]
Suggestion: put the warning on its own line in red if possible?

**Comment by spficklin** [comment]
I'm good with it.  I like it.

**Comment by laceysanderson** [comment]
I made the warning more prominent as shown below. Thanks for the feedback!
![db_module-db_table_warning](https://user-images.githubusercontent.com/1566301/35167998-08ce86c6-fd1d-11e7-97bd-f6c4f9483d3a.png)

**Comment by laceysanderson** [comment]
I went ahead and tested the documentation out on GitHub :-D
### GitHub Hosted Version: [laceysanderson.github.io/chado-docs](https://laceysanderson.github.io/chado-docs/index.html)

I decided to make it a separate repo from Chado in order to not further bloat the git history every time we update the documentation. My intent is that once everyone here signs off on it, I'll transfer ownership of the repo to the GMOD organization which will change the URL to `http://GMOD.github.io/chado-docs`.

The [Chado-Docs Repo](https://github.com/laceysanderson/chado-docs) contains all the documentation, as well as, the scripts used to build it. It will also contain a verbose README for how to rebuild the docs in the future.

@spficklin I'm not sure if we still want to bother with a docker image? The docker image would need to 1) install Java 8, Graphviz & PostgreSQL, 2) Download SchemaSpy and PostgreSQL Driver JARs, 3) Checkout Chado and Chado-Docs repositories, 4) Run a single command :-)

**Comment by spficklin** [comment]
@laceysanderson it's not a problem to have all of that in a Docker image.   I can make it so that we can provide the Chado version as input on the command-line when the image is run and then have it ask for GitHub credentials so that once it's done it can automatically generate the new documentation on a separate branch in the chado-docs repository.   That should make it really easy to regenerate anytime someone wants to.

By the way, to make that warning message more clear how about this text instead:

> The entity-relationship (ER) diagram below will show other tables that have a foreign key relationship with this one.  When a table belongs to a different Chado module and has a foreign key with this table then the table name will be prefixed with the module name.  Tables that are in the same module as this table do not have a prefix.  The prefix is meant to help clarify module membership. In actuality, you should not prefix tables with the module when performing SQL queries.

**Comment by spficklin** [comment]
I have to say, I like this new SchemaSpy docs.  I wanted to know what were all the tables linked to by the Contact table and I came straight to @laceysanderson new chado-doc repository.  Very handy!

**Comment by laceysanderson** [comment]
Please see https://github.com/GMOD/Chado/issues/72 for more discussion on general documentation.

**Comment by bradfordcondon** [comment]
I like lacey's suggestion of having this wholesale in the schema.  

@laceysanderson do you think we should host the code from https://github.com/laceysanderson/chado-docs here in this repo?  Or should i instead write a build script in this repo that pulls in your chado-schema repo?

**Comment by laceysanderson** [comment]
I would love the code in https://github.com/laceysanderson/chado-docs hosted here and will transfer ownership as soon as someone gives me the word :-)

**Comment by bradfordcondon** [comment]
I've been working on this.  I've been successful just putting the built schemaspy site into the `_static` folder of the docs, and then linking to it on the docs landing page.

Ideally, I'd like either the Travis CI or the RTD to build the schemaspy site.  Travis would do something like rebuild and push to a documentation branch (not unlike how `gh-pages` works.).  I have flyway installed using Gradle so in theory there are [schemaspy gradle plugins](https://github.com/tresat/gradle-schemaspy-plugin) that would make it easy to build the schemaspy site in travis then copy it into the `docs/_static`.

RTD seems harder.  I think we would need a python extension and/or I dont know that we can have java in the RTD build.

**Comment by bradfordcondon** [comment]
DONE!
You can find the documentation here https://chado.readthedocs.io/en/rtd/index.html

And the schemaspy documentation here: https://chado.readthedocs.io/en/rtd/_static/schemaspy_integration/index.html
