### ISSUE TITLE
Core Goal: Defining Contribution Guidelines and Governance

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#63]
The issue of governance came up during our groups module meeting today.  [Meeting notes here](https://docs.google.com/document/d/1J3KVdavfjEXqeZ6tBR_5yDDEaZzSJF9VqM086SEC2wM/edit#).

[We are having a similar discussion in Tripal right now.](https://github.com/tripal/tripal/issues/344)
In that meeting I started the discussion by linking [this guide for open source structures](https://opensource.guide/leadership-and-governance/#what-are-some-of-the-common-governance-structures-for-open-source-projects).

We thought the community would benefit from some formalized governance by
* reducing work overload and reliance on @scottcain 
* developing faster
* being more cohesive in terms of implementation

This thread is for discussion on what a Chado governance structure would look like.  

Some questions...
* Would it make more sense to organize at the GMOD level?
* What do we require of contributions?  In terms of documentation, usage guide, commenting, the migration script stuff...
* What do we require of someone who will have write access to the repo?

**Comment by laceysanderson** [comment]
Yes, even if you remain our benevolent dictator @scottcain, it would be great to have documentation of what is required both theory and code-wise to extend Chado. That way, users wanting to extend Chado could do most (if not all) of the work.

**Comment by scottcain** [comment]
Along with establishing a new governence model, we probably also want to look at how different types of additions are accepted.  Generally, there are four types of commits (only for the schema--perl code and documentation are different):

1. Adding something "small", like indexes or a single field to an existing table.
2. A little bigger is adding a linking table (but really, still fairly small).
3. Kind of medium sized would be new, non-linking tables to existing modules.  I can't off the top of my head thing of an example of this, but I'm pretty sure it's happened.
4. Adding whole new modules.

These really ought to be handled differently.  New indexes can be added almost immediately.  While we don't want to add indexes willy-nilly (poor index creation can result in confusing the query planner), if someone says "I have this query that really needs this index" then after sending an email to the mailing list and waiting a short period of time, it probably can be added.  New linking tables should get approximately the same treatment, since they are even less likely to have an adverse effect on the data, other than one more unused table by people who don't need it.  So a brief explanation of why the table is needed to the mailing list and waiting a short time for discussion seems like enough.

Adding other types of tables to existing should get a little closer scrutiny, answering questions along the lines of is it generic and likely to be generally useful.

Adding new modules should involve full blown use cases and will take a while to add, but fortunately doesn't happen very often.

**Comment by spficklin** [comment]
I think new modules should be implemented and used in production on at least one site/tool to demonstrate scaleability as well.  If the ND module had had that requirement someone would have discovered issues with it before it got merged into Chado.

> New linking tables should get approximately the same treatment, since they are even less likely to have an adverse effect on the data, **other than one more unused table by people who don't need it.**

Love it.

**Comment by bradfordcondon** [comment]
Here are the notes i took for our governance meeting.

https://docs.google.com/document/d/1M-fEnIV7QcMiL4dEjNEH9NXJud7BL8-EV6VGeClqwkA/edit#heading=h.m0yxwd4rs0jn

**Comment by bradfordcondon** [comment]
Approved and merged!  If any questions or suggestions arise, please feel free to create new issues.  Thank you to all, especially @laceysanderson for drafting the PR.
