### ISSUE TITLE
Should modules continue to exist?

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#90]
Schema management is greatly improved by flyway.  However it raises the question of modules.
Namely, should we simplify Chado and merge them?

#### Remove modules

Have a single SQL file for chado setup.  Then, we have a single migrations folder.
#### Keep modules

We'd have to test this out to make sure its feasible, but...
- each module has a single SQL file to install
- Each module has its own migrations to run

The flyway migrations parameter is an array, so sites would just list the modules they want to include.  Assuming there would be no problems with overlapping version names for migration scripts, it might be possible.  However, its still a question if its worth the added work of maintaining them separately.

**Comment by bradfordcondon** [comment]
i did some experimenting.  you can have multiple migration folders quite easily.... **but** the versions must be unique.

So we could split up migrations by module, but would need to take care that the versions dont overlap (and travis would tell us if we goof up)

**Comment by bradfordcondon** [comment]
pinging this issue again, I know the week after PAG is as blur.

**Comment by laceysanderson** [comment]
I’m in favour of dropping support for modules. The dependencies between modules is such that I feel installing a single module is complicated at best. Thus I don’t feel it’s worth the complexity it would add to maintenance 🤷‍♀️

**Comment by ekcannon** [comment]
The concept of a module in chado seems to be rather weak, not only because of the dependencies that Lacey mentioned, but also because of the common practice of pulling useful tables from various modules to serve a different purpose than initially intended, for example, the eimage table. However, it is handy to have tables grouped. For example, when I adopted chado for some of the MaizeGDB data, I didn't want the whole schema, but was able to quickly grab the bulk of the tables I needed by bringing in full modules, then added additional tables as needed. 

Maybe the concept of a "module" should be changed to a looser concept of a "group".

**Comment by spficklin** [comment]
I do like the concept of keeping modules as table "groups" to simplify documentation and training others to use the tables.  In terms of creating module-specific SQL files I agree that it adds a bit too much complexity especially because we have so many linker tables that bridge modules and could actually be in more than one module.

**Comment by bradfordcondon** [comment]
Newly formed PMC all in favor of merging the **schema** to simplify managing it.   Documentation will remain split by module.
